# dimensions and sizes
geom_dim: 5
edge_type: door
inter_geom_dim: 2
cats_dim: 13
node_dim: 128
edge_dim: 128
graph_dim: 1024
num_layers: 5
# network settings
matching: true
message_gain: 0.1
graph_reg: false
graph_vec_weight: 1e-6
aggr: add
# optimization
cuda: true
distance: margin
margin: 1
n_epochs: 100
lr: 1e-4
bs: 32
step: 10
# data
graph_type: universal
sparse_graphs: true
p_axes: 0.2
p_points: 0.05
margin_axes: 0.1
margin_points: 0.1
# paths
path_checkpoint: .\checkpoints
path_data: \Users\caspervanengel\OneDrive\Documents\PHD\1_data\rplan\0-full
# remaining
print_freq: 100
